"""empty message

Revision ID: 318c0ca96f28
Revises: dab9d8d77e56
Create Date: 2018-06-18 14:50:13.106641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '318c0ca96f28'
down_revision = 'dab9d8d77e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email',
    sa.Column('email_addr', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('email_addr'),
    sa.UniqueConstraint('email_addr')
    )
    op.drop_index('email_addr', table_name='email')
    op.drop_table('email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('email_addr', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('email_addr'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email_addr', 'email', ['email_addr'], unique=True)
    op.drop_table('user_email')
    # ### end Alembic commands ###
