"""empty message

Revision ID: dab9d8d77e56
Revises: d35525e905d2
Create Date: 2018-06-18 14:34:42.052651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab9d8d77e56'
down_revision = 'd35525e905d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('email_addr', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('email_addr'),
    sa.UniqueConstraint('email_addr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###
